version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - roc-postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
  redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379
    volumes:
      - roc-redis-data:/data
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - roc-redis-insight:/data
volumes:
  roc-redis-insight:
  roc-postgres-data:
  roc-redis-data:
